#Server
server.port=8080

#Application name
spring.application.name=product

#Mongo
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=products
spring.data.mongodb.username=carlos
spring.data.mongodb.password=secretos123
spring.data.mongodb.authentication-database=admin


#Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.listener.missing-topics-fatal=false

#Logging levels
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.chstore.product=DEBUG
